export const loginTypes = {
	REQUEST: "LOGIN_REQUEST",
	SUCCESS: "LOGIN_SUCCESS",
	FAILURE: "LOGIN_FAILURE",

	LOGOUT: "LOGOUT",

	GET_TOKEN_REQUEST: "GET_TOKEN_REQUEST",
	GET_TOKEN_SUCCESS: "GET_TOKEN_SUCCESS",
	GET_TOKEN_ERROR: "GET_TOKEN_ERROR",

	REFRESH_OAUTH2_TOKEN_REQUEST: "REFRESH_OAUTH2_TOKEN_REQUEST",
	REFRESH_OAUTH2_TOKEN_SUCCESS: "REFRESH_OAUTH2_TOKEN_SUCCESS",
	REFRESH_OAUTH2_TOKEN_ERROR: "REFRESH_OAUTH2_TOKEN_ERROR",

	REFRESH_ACCESS_TOKEN_REQUEST: "REFRESH_ACCESS_TOKEN_REQUEST",
	REFRESH_ACCESS_TOKEN_SUCCESS: "REFRESH_ACCESS_TOKEN_SUCCESS",
	REFRESH_ACCESS_TOKEN_ERROR: "REFRESH_ACCESS_TOKEN_ERROR",
};
